version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - etc:/etc/pihole/
      - etc-dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - "53:53"
      - "53:53/udp"
      - "67:67/udp"
      - "7080:80/tcp"
      - "7443:443/tcp"
    secrets:
      - password
    environment:
      TZ: 'Europe/Amsterdam'
      IPv6: 'False'
      WEBPASSWORD_FILE: '/run/secrets/password'
    dns:
      - 127.0.0.1
      - 192.168.1.1

volumes:
  etc:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.1.150,nolock,soft,rw
      device: ":/opt/nfs/volumes/pi-hole/etc"
  etc-dnsmasq.d:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.1.150,nolock,soft,rw
      device: ":/opt/nfs/volumes/pi-hole/etc-dnsmasq.d:"
    
secrets:
  password:
    external: true
    name: pi-hole-password
