version: "3.8"

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Amsterdam'

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/heimdall_config"
