version: '3.8'

services: 
  adguardhome:
    image: adguard/adguardhome:armhf-latest
    container_name: adguardhome
    placement:
      constraints:
        - "node.role==manager"
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf 
    ports:
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "853:853"
      - "3000:3000"

volumes:
  adguard-work:
    driver: local
  adguard-conf:
    driver: local
