version: '3'

services: 
  portainer:
    image: adguard/adguardhome:armhf-latest
    container_name: adguardhome
    restart: always
    network_mode: host
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf 
    ports:
      - "53:53"
      - "80:80"
      - "443:443"
      - "853:853"
      - "3000:3000"

volumes:
  adguard-work:
    driver: local
  adguard-conf:
    driver: local
