version: '3.8'

services:
  jackett:
    image: linuxserver/jackett:arm32v7-latest
    container_name: jackett
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
      - type: volume
        source: blackhole
        target: /condownloadsfig
        volume:
          nocopy: true
    ports:
      - "9117:9117"
    environment:
        PUID: '1000'
        PGID: '1000'
        TZ: 'Europe/Amsterdam'
        AUTO_UPDATE: 'true'

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/jackett/config"
  blackhole:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/jackett/blackhole"


