version: "3.8"

services:
  organizr:
    container_name: organizr
    image: linuxserver/organizr:arm32v7-latest

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
    ports:
      - "9983/80"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Amsterdam'

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/organizr_config"

