version: '3'

services: 
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    network_mode: portainer_agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
      - "8000:8000"
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer
    restart: always
    network_mode: portainer_agent_network
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-agent-volumes:/var/lib/docker/volumes
    ports: 
      - "9001:9001"

volumes:
  portainer-data:
    driver: local
  portainer-agent-volumes:
    driver: local
