version: '3.8'

services: 
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
      - "8000:8000"
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-agent-volumes:/var/lib/docker/volumes
    ports: 
      - "9001:9001"

volumes:
  portainer-data:
    driver: local
  portainer-agent-volumes:
    driver: local

networks:
  overlay:
