version: '3.8'

services:
  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    environment:
      AGENT_CLUSTER_ADDR: task.agent
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: data
        target: /data/
        volume:
          nocopy: true
    ports:
      - "9000:9000"
      - "8000:8000"

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/portainer_data"
  agent-volumes:
    driver: local

networks:
  agent_network:
    driver: overlay
    attachable: true
