version: "3.8"

services:
    letsencrypt:
      container_name: letsencrypt
      image: linuxserver/letsencrypt:arm32v7-latest
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      volumes:
        - config:/config
      ports:
        - "443:443"
      secrets:
        - password
      environment:
        PUID: '1000'
        PGID: '1000'
        TZ: 'Europe/Amsterdam'
        URL: 'simo.fyi'
        SUBDOMAINS: 'www, *.home.ams'
        VALIDATION: 'http'
        ONLY_SUBDOMAINS: 'false'
        FILE__PASSWORD: '/run/secrets/password'

volumes:
  config:
    driver: local
    
secrets:
  password:
    external: true
    name: letsencrypt-password
















