version: "3.8"

services:
  mongo:
    image: webhippie/mongodb:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    volumes:
      - type: volume
        source: backup
        target: /var/lib/backup
        volume:
          nocopy: true
      - type: volume
        source: mongodb
        target: /var/lib/mongodb
        volume:
          nocopy: true
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    networks:
      - databases
    secrets:
      - password_root
    environment:
      MONGODB_AUTH: "false"
      MONGODB_AUTH_DB: "admin"
      MONGODB_DATABASE: "default"
      MONGODB_USERNAME: "username"
      MONGODB_PASSWORD: "username"
      MONGODB_PERFORM_REPAIR: "true"
      MONGODB_PERFORM_UPGRADE: "true"
      MONGODB_ROOT_PASSWORD: "root"
      MONGODB_ROOT_USERNAME: "root"

volumes:
  backup:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/mongo/backup"
  mongodb:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.150,rw
      device: ":/opt/nfs/volumes/mongo/mongodb"

secrets:
  password_root:
    external: true
    name: mongo-password-root

networks:
  databases:
    driver: overlay
    attachable: true
