version: '3.8'

services:
  unifi:
    image: jacobalberty/unifi:latest
    container_name: unifi
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - unifi:/unifi
      - run:/var/run/unifi
    ports:
      - "3478:3478/udp"
      - "5514:5514"
      - "8080:8080"
      - "8443:8443" 
      - "8843:8843" 
      - "8880:8880"
      - "6789:6789"
      - "27117:27117"
      - "5656-5699:5656-5699/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
    environment:
      RUNAS_UID0: 'false'
      UNIFI_HTTP_PORT: '8080'
      UNIFI_HTTPS_PORT: '8443'
      UNIFI_UID: '1000'
      UNIFI_GID": '1000'
      TZ: 'Europe/Amsterdam'


volumes:
  unifi:
    driver: local
  run:
    driver: local
