version: '3.8'

services:
  unifi:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - config:/config
    ports:
      - target: 3478 # STUN
        published: 3478
        protocol: udp
        mode: host
      - target: 10001 # AP discovery
        published: 10001
        protocol: udp
        mode: host
      - "8080:8080" # Controller GUI/API as seen in a web browse
      - "8081:8081"
      - "8443:8443"
      - "8843:8843" # HTTPS portal redirection
      - "8880:8880" # HTTP portal redirection
      - "6789:6789" # For throughput test
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional

volumes:
  config:
    driver: local
