version: '3.8'

services:
  unifi:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - "node.labels.unifi==true"
    volumes:
      - config:/config
    ports:
      - target: 3478 # Port used for STUN.
        published: 3478
        protocol: udp
        mode: host
      - target: 10001 # Port used for device discovery
        published: 10001
        protocol: udp
        mode: host
      - target: 1900 # Port used for "Make controller discoverable on L2 network" in controller settings.
        published: 1900
        protocol: udp
        mode: host
      - target: 8080 # Port used for device and controller communication.
        published: 8080
        protocol: tcp
        mode: host
      - "8443:8443" # Port used for controller GUI/API as seen in a web browser
      - "8843:8843" # Port used for HTTPS portal redirection.
      - "8880:8880" # Port used for HTTP portal redirection.
      - "6789:6789" # Port used for UniFi mobile speed test.
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional

volumes:
  config:
    driver: local
